Time conversion done using array of timezones
aej11a/icdb-345 pull request #13
Opened 2021-04-21 02:31 UTC by BlackRoseRipp

2021-04-21 15:47 UTC, JDPablo commented
Getting times greater than 12 sometimes appended by am or pm (try EST->JST 11:45am)

2021-04-21 15:49 UTC, JDPablo commented
Line 46 crashes bot attempting to run "!DocBrown EDT->JDT 11:45am"

2021-04-21 16:31 UTC, aej11a requested changes

2021-04-21 16:31 UTC, ajones55555 commented on app.js
> +const timezoneCodes = [
Can you move this array declaration and also the currency codes array declaration to another file?
Then at the top of this file, do something like `const { currencyList, timezoneList } = require('./supportedConversions')`

2021-04-21 16:31 UTC, ajones55555 commented on app.js
> +    const content = msg.content.slice(10).toUpperCase().trim().split(' ') //10 is the length of '!DocBrown '
Hardcoding these numbers isn't really a sustainable approach as we keep adding more commands.
Can you add an enum object _near the top of the file_ to track supported commands?
For example: 
```
// at the top
const supportedCommands = {
     convertTimes: '!DocBrown',
     setup: '!Setup'
}
```

and then anywhere where we need !DocBrown or !Setup, replace it with `supportedCommands.________`

2021-04-21 22:50 UTC, BlackRoseRipp commented on app.js
> +    const content = msg.content.slice(10).toUpperCase().trim().split(' ') //10 is the length of '!DocBrown '
Added it. We could add that to the supportedConversions file instead if we keep adding commands

2021-04-22 21:49 UTC, aej11a approved these changes

2021-04-22 21:49 UTC, merged